### ISSUE TITLE
User controller error for old express-serve-static-core

### ISSUE THREAD

**Issue by Aragonbn90** [jhipster/generator-jhipster-nodejs#120]
**Describe the bug**
User controller got typescript error.

**To Reproduce**

1. Use generator-jhipster v 6.8.0, generator-jhipster-nodejs v1.0.1
2. Create new project:
`mkdir my-app && cd my-app`
`jhipster --blueprints nodejs`
---- Choose Monolithic, JWT, MySQL, React, Default Jhipster theme
`cd server && npm install`
`npm start`

**Expected behavior**
src/web/rest/user.controller.ts:29:54 - error TS2345: Argument of type 'string | string[] | Query | Query[]' is not assignable to parameter of type 'string | number'.
`const pageRequest: PageRequest = new PageRequest(**req.query.page**, req.query.size, req.query.sort);`

**Desktop (please complete the following information):**
-   OS: Windows 10 

**Additional context**
I've tried on 2 Windows PC and got the same error. 
With generator-jhipster-nodejs v1.0.0 I've used before, there's no this kind of error.

**Comment by amanganiello90** [comment]
HI @Aragonbn90 , thanks for the feedback!!
Maybe it's a problem of external dependencies, because from v1.0.0 to v1.0.1 it is changed only a thing about the files not published (#118 , your issue). Then, the integration tests for these versions were ok after the release (the integration tests run also the application with a lot of configuration as your) : https://github.com/jhipster/generator-jhipster-nodejs/runs/535960015

**Comment by amanganiello90** [comment]
Thanks! All perfect! Now you are an official contributor ;) ..https://github.com/jhipster/generator-jhipster-nodejs#contributors-
