### ISSUE TITLE
Error when fetch list of entities from react client

### ISSUE THREAD

**Issue by Aragonbn90** [jhipster/generator-jhipster-nodejs#155]
**Describe the bug**
With Reactjs as client framework, error when fetch list of entities:
`Error: section could not be split on ";"`

**To Reproduce**

1. Login
2. Click on Entities/YOUR_ENTITY
`Error: section could not be split on ";"
    at url-utils.ts:24
    at Array.forEach (<anonymous>)
    at push../node_modules/react-jhipster/lib/src/util/url-utils.js.exports.parseHeaderForLinks (url-utils.ts:20)
    at ./src/main/webapp/app/entities/region/region.reducer.ts.__webpack_exports__.default (region.reducer.ts:72)`

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser Edge chromium

**Causion**
At server/src/client/header-util.ts:
- Line 57: `res.set('Link', links.join('%2C'));`
- Line 59: `<${url}>%3B rel="${relType}"` 
We're using "%2C", "%3B" to join.
But at .../entities/ENTITY.reducer.ts line 72: `const links = parseHeaderForLinks(action.payload.headers.link);` we're using `p.split(';')`

**Solution**
Change '%2C' to ','
Change '%3B' to ';'

**Comment by amanganiello90** [comment]
Hi @Aragonbn90 thanks for the issue! You are the best framework tester ;)
So I think that the error is related to the jhipster client side, I will update the version from the actual 6.8.0 to the latest in order to resolve also the entity generator bug.
However, you have found a solution in the server side, but indeed I don't know much about pagination because it is a feature inherited from a jhipster developer contribution, so I don't know what are the link and join with "%2C" or"%3B".

Could you do the fix that you have suggested and test that is all ok also with the angular client? Thanks

**Comment by Aragonbn90** [comment]
Hi @amanganiello90, I will try with this issue. Thank you for your client side suggest.

**Comment by amanganiello90** [comment]
Thanks, it works!
