### ISSUE TITLE
enum type values not correctly mapped in the server side

### ISSUE THREAD

**Issue by Aragonbn90** [jhipster/generator-jhipster-nodejs#156]
**Describe the bug**
Enum type at server side is not set value.

**To Reproduce**

1. Generate entity with enum column, such as: ONE,TWO,THREE 
2. Start app
3. Add new record with enum value ONE
sql error: 

**Expected behavior**
Created record with enum value 'ONE'

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser: Edge chromium

**Caution**
file /server/src/domain/enumeration/enum-type.ts done have value. It is: 
`EnumType {
    ONE,
    TWO,
    THREE
}`
Then Mysql generate column with value '0', '1', '2'

**Solution**
change file enum-type.ts to:
'`EnumType {
    ONE = 'ONE',
    TWO = 'TWO',
    THREE = 'THREE'
}`'

**Comment by amanganiello90** [comment]
Hi @Aragonbn90 , thanks for the feedback!
So the issue is due to the [template],(https://github.com/jhipster/generator-jhipster-nodejs/blob/master/generators/entity-server/templates/server/src/domain/enumeration/Enum.ts.ejs), we have to replace the *enumValues* with the literal object as explained in your example.

Maybe we have to generate e2e entity test more useful without entityMock object in [test template](https://github.com/jhipster/generator-jhipster-nodejs/blob/114c2461549be58a853659b11a06d7d2641a154d/generators/entity-server/templates/server/e2e/entity.e2e-spec.ts.ejs#L15), that is with real sqlite query. In this way we can check eventual bugs in the test integration pipeline.

Would you fix this issue? As just said, You have to do this step:
- Fill the [enumValues](https://github.com/jhipster/generator-jhipster-nodejs/blob/114c2461549be58a853659b11a06d7d2641a154d/generators/entity-server/templates/server/src/domain/enumeration/Enum.ts.ejs#L5) variable with the string list. You can do it replacing *enumValues* with a new variable to use in that template, for example *enumStringValues*. The last is created in the [imports.js](https://github.com/jhipster/generator-jhipster-nodejs/blob/114c2461549be58a853659b11a06d7d2641a154d/generators/entity-server/templates/server/src/domain/imports.ejs#L64) template, where you iterate the *enumValues* variable in order to fill the *enumStringValues* with string values.

For the test task, maybe it is a bit difficult and I could do it in future if for you is complicated. it requires to
Add new programmatically fields without [entityMock variable](https://github.com/jhipster/generator-jhipster-nodejs/blob/114c2461549be58a853659b11a06d7d2641a154d/generators/entity-server/templates/server/e2e/entity.e2e-spec.ts.ejs#L15) according the entity generated. It will call the service without mock using generated test field type as in [java template](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs).

**Comment by amanganiello90** [comment]
Thanks for the feedback, the bug is been fixed!
![screen](https://user-images.githubusercontent.com/20536757/89405384-c193d000-d71b-11ea-8f78-09b99561ec3d.png)
