### ISSUE TITLE
Getting 404 in PROD - Accessing static Angular via URL in the browser

### ISSUE THREAD

**Issue by ecirilo** [jhipster/generator-jhipster-nodejs#170]
**Describe the bug**
I'm getting 404 when I try to access Angular Routers directly from the browser or using Postman. Navigating via application it is working fine.

**To Reproduce**

1. Go to browser or Postman
2. Write any valid application URL
4. See 404 - Not found

**Expected behavior**
It is expected to show the corresponding page associated with the given URL (route)

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Mac OS X
-   Browser Firefox
![Screen Shot 2020-09-29 at 21 58 55](https://user-images.githubusercontent.com/38891000/94631752-31978000-029f-11eb-8a3a-d326ce9a84a6.png)

**Comment by amanganiello90** [comment]
Hi, thanks for the interest!
I have some questions for you:
+ Could you add your yo-rc.json file?
+  How do you start the application? If you start only the client side, the localhost:8081 is not the default url (usually it is localhost:4200)

**Comment by ecirilo** [comment]
Hi,

I have start the application locally, but as like in the production mode (client side served as static assets by the server side). 

I found a workaround/solution as suggested in such a Stackoverflow question: 
https://stackoverflow.com/questions/54838260/how-to-redirect-all-routes-to-index-html-angular-in-nest-js

I implemented the solution B) Global Error Filter. However, I'm not sure about whether it is the best solution.

Thanks ...

**Comment by amanganiello90** [comment]
What is the npm task that you have performed?
Because if you run with **npm start** in the root folder of the generated project, it will be run angular client on localhost:4200 without nestjs server.

**Comment by ecirilo** [comment]
Yes! I'm not running **npm start** in the project root folder. 

I did as follow: 
(i) built the app with **npm run build task** 
(ii) copied the **dist folder** to another location in my local environment.
(iii) started the application running **npm start**

It is important to note that I'm observing the same error on the production environment as well. The application and all internal links are working fine while I open **www.mydomain.com/**, however, if I open **www.mydomain.com/category** the server falls with 404 ...

**Comment by amanganiello90** [comment]
Ok, but it has not sense the npm start in an other folder with the static build files. The reason is that you don't have a web server for static resources with the npm start command (it is for building and serving on time source files).

**Comment by ecirilo** [comment]
It seems that I'm missing some step. How do I have to proceed in order to deploy my app after run **npm run build task**? Which are the recommend steps. The cloud server that I'm using automatically starts NodeJS apps running **npm start**.

As I  mentioned ... these are the steps I'm following
(i) run npm build task
(ii) deploy the dist folder on the production environment (I have a package.json which executes **node dist/main** as a **start** task)
(iii) the production environment automatically run **npm start**

**Comment by amanganiello90** [comment]
Hi @ecirilo ,
Do you want only to build and run the angular client? In this case after the **npm run build** you will have under dist folder only web resources (html, javascript, css compiled from angular app) that are used from a web server (tomcat, netty, nginx) or published (the content of the dist folder) with a service that host your web resources : https://code.makery.ch/library/html-css/part2/

So it has only static web resources, it **does not require a nodejs application server**.

Instead if you generate an application with client and server part, you can choise to build the entire stack with **npm run build:app** and after run under server folder the command **npm run start:prod**.

In the last it will be run a nodejs server with static client and nestjs backend already compiled. So here is mandatory the application server because you have some backend request to process.

**Comment by amanganiello90** [comment]
If there aren't any questions I think that this ticket is completed. Feel free to open another issue for any questions or problems. Thanks.
