### ISSUE TITLE
There will be validation, dto and NestJS 7 in next release?

### ISSUE THREAD

**Issue by BartEvers** [jhipster/generator-jhipster-nodejs#180]
Hi,

Do you have any idea as to when the nest release will be? I am specifically interested in the following planned features:

-  DTOs based rest api
- Validation

Also, will you be using NestJS 7 any time soon?

Keep up the good work, Angelo & team!

**Comment by amanganiello90** [comment]
Hi @BartEvers,
thanks for the interest!
So...the validation it is already added in the entity classes(min, max, notNull and so on). But do you refers dto validations?

However, the [last release](https://github.com/jhipster/generator-jhipster-nodejs/releases/tag/v1.3.0) is been published few days ago, and there are other issues in the [kanban board](https://github.com/jhipster/generator-jhipster-nodejs/projects/1#card-28557891) that I have not chosen the priority yet.
You can open a new issue per feature and/or comment on that you prefers to do in the next release.
For now I open the three feature that you have explained in order to trace the status. Thanks

**Comment by amanganiello90** [comment]
I have just created the issues related to your features:

- DTO: https://github.com/jhipster/generator-jhipster-nodejs/issues/181
- Validation: https://github.com/jhipster/generator-jhipster-nodejs/issues/182
- Nestjs 7 update: https://github.com/jhipster/generator-jhipster-nodejs/issues/183

You can comment those adding details or/and open new issues. Thanks

**Comment by BartEvers** [comment]
Thanks Angelo!

**Comment by BartEvers** [comment]
> So...the validation it is already added in the entity classes(min, max, notNull and so on). But do you refers dto validations?

Well, in the [roadmap](https://github.com/jhipster/generator-jhipster-nodejs/blob/main/ROADMAP.md) you have an open issue called **Validation**. I was wondering; is this point from the roadmap referring to validations in general of validations in DTO's?

**Comment by amanganiello90** [comment]
> 
> 
> > So...the validation it is already added in the entity classes(min, max, notNull and so on). But do you refers dto validations?
> 
> Well, in the [roadmap](https://github.com/jhipster/generator-jhipster-nodejs/blob/main/ROADMAP.md) you have an open issue called **Validation**. I was wondering; is this point from the roadmap referring to validations in general of validations in DTO's?

DTO's validation... the issue that I have just opened #182 explains that scope.

**Comment by BartEvers** [comment]
Clear, thanks!

**Comment by amanganiello90** [comment]
Done with 1.4.0 release.
