### ISSUE TITLE
Remove CLI and use jhipster CLI 

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster-nodejs#2]
Lets not use a separate CLI here. Blueprints should use jhipster cli and specify the blueprint name so that when we get multiple blueprint working we can interop without issues. Also it avoids fragmentation

**Comment by amanganiello90** [comment]
Hi @deepu105, I have added a cli script as [kotlin blueprint](https://github.com/jhipster/jhipster-kotlin).
it is not tested yet, and in my opinion is not a problem to provide another type of installation, also because it's the same jhipster running way (change only the installation and the execution command)

**Comment by amanganiello90** [comment]
cli removed in #21. Thanks
