### ISSUE TITLE
(Global) rimraf: command not found

### ISSUE THREAD

**Issue by manekinekko** [jhipster/generator-jhipster-nodejs#43]
**Describe the bug**
Following the installation steps (and those for jhipster). I am getting this error:

```
sh: rimraf: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! tmp@0.0.1-SNAPSHOT cleanup: `rimraf target/classes/static/ target/classes/aot`
npm ERR! spawn ENOENT
npm ERR! 
```

**To Reproduce**
1. `git clone git@github.com:jhipster/generator-jhipster-nodejs.git`
2. `cd $_`
2. `npm i`
2. `npm link .`
2. `npm i -g yo`
2. `npm i -g generator-jhipster`
2. `take /tmp/demo-app`
2. `jhipster --blueprint nodejs`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1699357/65181613-bc745680-da5f-11e9-9678-f4c5a5594289.png)

**Additional context**
Either jhipster or this nestjs blueprint assume that the `rimraf` package is installed globally. However, in the nodejs/javascript community we dont recommend installing such packages globally (for security reasons).

A possible fix for this issue is to install the `rimraf` package as a dev dependency locally to the project and call the binary from the local `./node_modules`.

**Comment by amanganiello90** [comment]
Hi @manekinekko , thanks for your feedback!
I have a question for you.. do you have performed the **npm install** under the server folder? I tell you that, because, as you can view on the [server package.json sample app](https://github.com/jhipster/jhipster-sample-app-nodejs/blob/v1.0.0-alpha.1/server/package.json), there is rimraf a dependency. I have tested this sample app, so you can tell me all the commands that you have tried? Please refer to the general README and the server/README generated, so that you can give me more feedbacks and eventually a review for a better documentation. Thanks

**Comment by amanganiello90** [comment]
Hi @manekinekko, just a last advice... If you have still issues, run the blueprint with **jhipster --blueprint nodejs --skip-install**. Maybe it's a problem of a install hook. Thanks

**Comment by jdubois** [comment]
I've had those "rimraf" issues in the past, and I probably installed it globally to fix this, so I hope there isn't a bigger issue here

**Comment by manekinekko** [comment]
That's not something we recommend :)

**Comment by amanganiello90** [comment]
@manekinekko for me it' s very strange, I have run the generator in various machines without rimraf installed globally and it works.

**Comment by manekinekko** [comment]
@amanganiello90 FYI, `take` is a `zsh` command which creates and `cd` into a new folder.

I was also getting to open another issue where the installation process (of jhipster) is requesting me to install Java! But I'm gonna leave it here.

For context, as a Node and a JavaScript developer, I was called in by @jdubois to give my feedback on this project. My feeling so far is If this blueprint is aimed to bring Node and JavaScript developers to jhipster, you probably need to review and improve the installation, the getting started and DX processes so these developers feel welcomed.

Cheers.

**Comment by amanganiello90** [comment]
Hi @manekinekko 
I have already adds in the backlog the issue #44 in order to leave java, according other feedbacks. The only problema is that I can modify the blueprint, but not the basic jhipster standard CLI that you must install before, so if it requires for the installation Java, the developer should have almost a JRE on his machine. Otherwise, we have to add an optional or remove the constrant (and release a new version) in the basic **generator-jhipster**..it could be useful for all blueprints that not hava classes (as .Net bluprint)..Any suggestion @jbadeau ?

**Comment by jdubois** [comment]
Indeed Java shouldn't be a requirement anymore for the jhipster CLI.
I haven't followed this, but I think this is handled on the JHipster CLI side, @amanganiello90 do you have some more information? Can you add a ticket on jhipster/generator-jhipster so this is tracked?

**Comment by amanganiello90** [comment]
Hi @jdubois, 
There is a [java check](https://github.com/jhipster/generator-jhipster/blob/1e0faa826a79156a7aad6376a5028b140d4f9760/generators/info/index.js#L71) called from the [general app index.js](https://github.com/jhipster/generator-jhipster/blob/9e587ccc47a7f3f37b52b92079bc81ae85f37c53/generators/app/index.js#L240)...Should I open a ticket and try to resolve it? Thanks

**Comment by jdubois** [comment]
Yes, don't hesitate!! I'm clearly not doing everything in the project, the best and only way to get that kind of thing moving is through tickets, so the right person can take it. And if it doesn't move fast enough I can give bug bounties :-)

**Comment by amanganiello90** [comment]
OK wonderful!
