### ISSUE TITLE
Consider migrating from TSLint to ESLint for the generated part

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster-nodejs#55]
Hi, first of, you guys are doing an amazing job!

**Is your feature request related to a problem? Please describe.**
TSlint is to be deprecated (or already is) in favor of ESLint. And this generator already seems to use ESLint.

**Describe the solution you'd like**
Using ESLint instead of TSLint, and that includes changes in (not exhaustive I think):
  - the generated package.json file
    - dependencies
    - scripts
  - the TSLint conf files (removal)
  - new ESLint conf files (additions)

**Describe alternatives you've considered**
Maybe waiting a bit, if all the relevant rules are not yet implemented in ESLint (but I think everything's in order), this may need checking.

**Comment by amanganiello90** [comment]
Hi @MathieuAA,
Thanks a lot! Yes, I know the deprecation and there was already my intention the ESLint migration, also because the blueprint already uses ESLint for the templates.
There is [a useful tool](https://github.com/typescript-eslint/tslint-to-eslint-config) for this.
I will insert it into backlog. Thanks

**Comment by amanganiello90** [comment]
I will start this feature uniforming, as the client part, the lint task for the server (lint:fix instead of lint-fix)
