### ISSUE TITLE
dest is not a directory

### ISSUE THREAD

**Issue by kosnkow** [jhipster/generator-jhipster-nodejs#98]
when I run npm run build:app or npm run build as mentioned in readme (windows)
i get cp: dest is not a directory (to many sources)

it was not able to find config so when I moved this line ouf of the if (!fs.existsSync(out)) { it works

fs.mkdirSync(out + '/config');

**Comment by amanganiello90** [comment]
Thanks for your feedback!
But I don't understand your issues.
The [line](https://github.com/jhipster/generator-jhipster-nodejs/blob/master/generators/server/templates/server/scripts/copy-resources.ts.ejs#L5) is necessary because the dist folder must be created if it does not exist.
Maybe in your machine the ```fs.mkdirSync(out);``` fails without rises an error, so the cp command does not find the directory.
